# TCL File Generated by Component Editor 24.1
# Tue Jan 27 16:51:38 CET 2026
# DO NOT MODIFY


# 
# Osmanip "Osmanip" v2.0
#  2026.01.27.16:51:38
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module Osmanip
# 
set_module_property DESCRIPTION ""
set_module_property NAME Osmanip
set_module_property VERSION 2.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME Osmanip
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL controller_ip
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file controller_ip.vhd VHDL PATH "../../Code VHDL/controller_ip.vhd" TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter ADDR_WIDTH NATURAL 5
set_parameter_property ADDR_WIDTH DEFAULT_VALUE 5
set_parameter_property ADDR_WIDTH DISPLAY_NAME ADDR_WIDTH
set_parameter_property ADDR_WIDTH TYPE NATURAL
set_parameter_property ADDR_WIDTH UNITS None
set_parameter_property ADDR_WIDTH HDL_PARAMETER true
add_parameter ARRAY_SIZE NATURAL 32
set_parameter_property ARRAY_SIZE DEFAULT_VALUE 32
set_parameter_property ARRAY_SIZE DISPLAY_NAME ARRAY_SIZE
set_parameter_property ARRAY_SIZE TYPE NATURAL
set_parameter_property ARRAY_SIZE UNITS None
set_parameter_property ARRAY_SIZE HDL_PARAMETER true
add_parameter DATA_LENGTH NATURAL 8
set_parameter_property DATA_LENGTH DEFAULT_VALUE 8
set_parameter_property DATA_LENGTH DISPLAY_NAME DATA_LENGTH
set_parameter_property DATA_LENGTH TYPE NATURAL
set_parameter_property DATA_LENGTH UNITS None
set_parameter_property DATA_LENGTH HDL_PARAMETER true
add_parameter EXERNAL_DATA_LENGTH NATURAL 8
set_parameter_property EXERNAL_DATA_LENGTH DEFAULT_VALUE 8
set_parameter_property EXERNAL_DATA_LENGTH DISPLAY_NAME EXERNAL_DATA_LENGTH
set_parameter_property EXERNAL_DATA_LENGTH TYPE NATURAL
set_parameter_property EXERNAL_DATA_LENGTH UNITS None
set_parameter_property EXERNAL_DATA_LENGTH HDL_PARAMETER true
add_parameter START_ADDR NATURAL 31
set_parameter_property START_ADDR DEFAULT_VALUE 31
set_parameter_property START_ADDR DISPLAY_NAME START_ADDR
set_parameter_property START_ADDR TYPE NATURAL
set_parameter_property START_ADDR UNITS None
set_parameter_property START_ADDR HDL_PARAMETER true


# 
# display items
# 


# 
# connection point s1
# 
add_interface s1 avalon end
set_interface_property s1 addressUnits WORDS
set_interface_property s1 associatedClock clock_sink
set_interface_property s1 associatedReset reset_sink
set_interface_property s1 bitsPerSymbol 8
set_interface_property s1 burstOnBurstBoundariesOnly false
set_interface_property s1 burstcountUnits WORDS
set_interface_property s1 explicitAddressSpan 0
set_interface_property s1 holdTime 0
set_interface_property s1 linewrapBursts false
set_interface_property s1 maximumPendingReadTransactions 0
set_interface_property s1 maximumPendingWriteTransactions 0
set_interface_property s1 readLatency 0
set_interface_property s1 readWaitTime 1
set_interface_property s1 setupTime 0
set_interface_property s1 timingUnits Cycles
set_interface_property s1 writeWaitTime 0
set_interface_property s1 ENABLED true
set_interface_property s1 EXPORT_OF ""
set_interface_property s1 PORT_NAME_MAP ""
set_interface_property s1 CMSIS_SVD_VARIABLES ""
set_interface_property s1 SVD_ADDRESS_GROUP ""

add_interface_port s1 avs_s1_address address Input "((addr_width-1)) - (0) + 1"
add_interface_port s1 avs_s1_write write Input 1
add_interface_port s1 avs_s1_writedata writedata Input "((data_length-1)) - (0) + 1"
add_interface_port s1 avs_s1_read read Input 1
add_interface_port s1 avs_s1_readdata readdata Output "((data_length-1)) - (0) + 1"
set_interface_assignment s1 embeddedsw.configuration.isFlash 0
set_interface_assignment s1 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s1 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s1 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink avs_s1_clk clk Input 1


# 
# connection point external_connection
# 
add_interface external_connection conduit end
set_interface_property external_connection associatedClock clock_sink
set_interface_property external_connection associatedReset ""
set_interface_property external_connection ENABLED true
set_interface_property external_connection EXPORT_OF ""
set_interface_property external_connection PORT_NAME_MAP ""
set_interface_property external_connection CMSIS_SVD_VARIABLES ""
set_interface_property external_connection SVD_ADDRESS_GROUP ""

add_interface_port external_connection pio_out export Output 8


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink avs_s1_reset reset Input 1

